name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12', '14', '16']
        os: ['ubuntu-latest', 'windows-latest', 'macOs-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Use Nodejs ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
      
    - name: npm install build and test
      run: |
        npm install
        npm run build --if-present
        npm test
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag notekeep:$(date +%s)
